// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV8cGZqaeMEwha-gCYQM88loc9qiMM-TA',
    appId: '1:554381031992:web:cfdede0392a87c93b904cd',
    messagingSenderId: '554381031992',
    projectId: 'workoutapp-95a25',
    authDomain: 'workoutapp-95a25.firebaseapp.com',
    storageBucket: 'workoutapp-95a25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoGBMwg3TWtoqNz3ldMncxA4Vb1OL4S5E',
    appId: '1:554381031992:android:778a116d4608cbe3b904cd',
    messagingSenderId: '554381031992',
    projectId: 'workoutapp-95a25',
    storageBucket: 'workoutapp-95a25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPKRAKAlsQS8m32wZEfAqnEC6f9k09UOU',
    appId: '1:554381031992:ios:5f1b3f33e5c80464b904cd',
    messagingSenderId: '554381031992',
    projectId: 'workoutapp-95a25',
    storageBucket: 'workoutapp-95a25.firebasestorage.app',
    iosBundleId: 'com.kurs.workout.kurs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPKRAKAlsQS8m32wZEfAqnEC6f9k09UOU',
    appId: '1:554381031992:ios:5f1b3f33e5c80464b904cd',
    messagingSenderId: '554381031992',
    projectId: 'workoutapp-95a25',
    storageBucket: 'workoutapp-95a25.firebasestorage.app',
    iosBundleId: 'com.kurs.workout.kurs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV8cGZqaeMEwha-gCYQM88loc9qiMM-TA',
    appId: '1:554381031992:web:c78a89923f12ff93b904cd',
    messagingSenderId: '554381031992',
    projectId: 'workoutapp-95a25',
    authDomain: 'workoutapp-95a25.firebaseapp.com',
    storageBucket: 'workoutapp-95a25.firebasestorage.app',
  );
}
